version: '3.4'

services:
  nugetserver:
    restart: always
    hostname: ${NUGET_HOSTNAME:-nugetserver}
    container_name: nugetserver
    image: nugetserver:latest
    build:
      context: .\NugetServer
      dockerfile: Dockerfile
    volumes:
      - ${PACKAGES_FOLDER:-c:\packages}:c:\packages    
    networks:
      default:
        ipv4_address: 172.20.0.10
      
networks:
  default:
    external:
      name: nat